config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  
  root 'paginas#index'

  resources :organizacions
  resources :paginas

   

end

app/models/organizacion.rb
class Organizacion < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/organizacions_controller.rb
class OrganizacionsController < ApplicationController
	before_action :encontrar_organizacion, only: [:show, :edit, :update, :destroy]
	def index
		@organizacions = Organizacion.all.order("created_at DESC")
	end

	def show
	end

	def new
		@organizacion = Organizacion.new
	end

	def edit
		
	end

	def update
		if @organizacion.update(organizacion_params)
			redirect_to organizacion_path(@organizacion)
		else
			render 'edit'
		end
	end

	def destroy
		@organizacion.destroy

		redirect_to root_path

	end

	def create
		@organizacion = Organizacion.new(organizacion_params)
		if @organizacion.save
			
			render 'exito'	
		else
			render 'new'
		end
	end


	private

	def organizacion_params
		params.require(:organizacion).permit(:nombre,:direccion , :descripcion ,:telefono)
	end

	def encontrar_organizacion
		@organizacion = Organizacion.find(params[:id])
	end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
	def index
	end

	def registro_cliente
		
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizacions_helper.rb
module OrganizacionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Crumbik</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= yield :css_personalizado %>
	  
	  <%= csrf_meta_tags %>
	</head>


	<body>
		<%= render "partials/header" %>
		
		<% if alert %>
			<p class="alert">
				<%= alert %>
			</p>
		<% elsif notice %>
			<p class="notice"><%= notice %></p>
       	<% end %>	
	

		<div class="container">
			<%= yield %>
		</div>
	

		<%= render "partials/footer" %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= yield :javascript_personalizado %>
	</body>
</html>

app/views/organizacions/_form.html.erb
<%= simple_form_for @organizacion do |f| %>
  <%= f.input :nombre, label: 'Nombre de la Empresa: ' %>
  <%= f.input :direccion %>
  <%= f.input :descripcion %> 
  <%= f.input :telefono %>
     <%  @organizacion.estatus = 'activa' %>
  <%= f.button :submit, "Crear organizacion" %>
<% end %>

app/views/organizacions/edit.html.erb
<h1>Editar organizacion</h1>
<%= render 'form' %>

app/views/organizacions/exito.html.erb
<div class="jumbotron">
	<h2>Guardado con Exito</h2>
</div>

app/views/organizacions/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12" style="text-align : center;">
		
		

			<div class="list-group" >
				<% @organizacions.each do |organizacion| %>
					
 					<%= link_to organizacion.nombre, organizacion_path(organizacion) , :class => "list-group-item lefr"%></br>


  				<% end %>
			</div>
				
				 	
		
		</div>
	</div>
</div>

app/views/organizacions/new.html.erb
<div class="wrapper_skinny">
		<h1>Datos del administrador</h1>
	<div class="form-group string optional separador_inferior">
		<div class="form-group string optional">
			<label for="nombre_usuario" class="string optional control-label"> Nombre </label>
			<input type="text" class="string optional form-control">

			<label for="nombre_usuario" class="string optional control-label"> email </label>
			<input type="text" class="string optional form-control">

			<label for="nombre_usuario" class="string optional control-label"> contraseña </label>
			<input type="text" class="string optional form-control">

			<label for="nombre_usuario" class="string optional control-label"> confirme su contraseña </label>
			<input type="text" class="string optional form-control">
		</div>
	</div>

	<h1>Datos de la organizacion</h1>
	  
	 <%= render 'form' %>
</div>

app/views/organizacions/show.html.erb
<h1><%= @organizacion.nombre %></h1>
<ul>
	<li><%= @organizacion.descripcion %></li>
	<li><%= @organizacion.direccion %></li>
	<li><%= @organizacion.telefono %></li>
	<li><%= @organizacion.estatus %></li>

</ul>
<%= link_to "Atras", root_path %>
<%= link_to "Editar", edit_organizacion_path(@organizacion) %>

app/views/paginas/index.html.erb
<div class="container">
	
	
</div>

app/views/paginas/registro_cliente.html.erb
<div class="col-xs-12 center-block">
	<input type="text">
	
</div>

app/views/partials/_footer.html.erb
<div id="footer">
	<div class="">
		<div class="row">
			<div class="container" style="margin: 2rem auto;">
				<div class="col-md-3 texto_footer">
			 <div class="icon_footer_wrapper">
			 	<img id="logo"	src="<%= asset_path 'crumbikfoot.png' %>">
				<p class="blanco grande" style="line-height: 2rem; text-align: center;">Ll&aacute;manos</p>
				<div style="text-align: center;" >
					<span class="blanco grande " > 0500 - </span><span class="magenta grande"> 2783245</span> <span class="blanco grande"> - 00</span>
				</div>
				

			 </div>
				
			</div>
			<div class="col-md-3 texto_footer center-block">
				<h6 class="morado">QUICK LINKS</h6>
				<p class="blanco delgado"> Features</p>
				<p class="blanco delgado"> Pricing & Sign Up</p>
				<p class="blanco delgado"> Features</p>
			</div>
			<div class="col-md-3 texto_footer">
				<h6 class="rosado">RESOURCES</h6>
				<p class="blanco delgado"> Help Center</p>
				<p class="blanco delgado"> Certified Consultants</p>
				<p class="blanco delgado"> Demo Videos</p>
				<p class="blanco delgado"> Developer API</p>
				<p class="blanco delgado"> Blogs</p>
				<p class="blanco delgado"> User Community</p>
				<p class="blanco delgado"> Discussion Forum</p>

			</div>
			<div class="col-md-3 texto_footer">
				<h6 class="azul">ABOUT CRM</h6>
				<p class="blanco delgado"> what is CRM software</p>
				<p class="blanco delgado"> How CRM Works?</p>
				<p class="blanco delgado"> How To Evaluate CRM Software?</p>
				<p class="blanco delgado"> How To Buy CRM Software?</p>
				<p class="blanco delgado"> Compare CRM Software</p>
				<p class="blanco delgado"> New to CRM?</p>
			</div>
			</div>
			

		</div>
			<div class="row">
				<div id="iconos">
					<i class="fa fa-facebook fa-2x"></i>
					<i class="fa fa-twitter fa-2x"></i>
					<i class="fa fa-linkedin fa-2x"></i>
				</div>
			</div>
	</div>

</div>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid" >
  <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
       
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <a href="#" class="brand-logo ">
          <img src="<%= asset_path 'logo.png' %>">
        </a>
        <a href=<% new_organizacion_path %> > <span id="logo-text" class="navbar-brand" style="float: right; margin: 1.5rem 0 .5rem 0;">CR&Uuml;MBIK</span></a>
       
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="margin: 1.5rem 0 .5rem 0;">
      <ul class="nav navbar-nav navbar-right">
           
           <li><%= link_to "Inicio", root_path %> </li>
            <li><a href="#">Servicios</a></li>
            <li><a href="#">Planes</a></li>
            <li><a href="#">Cont&aacute;ctanos</a></li>
          <% unless usuario_signed_in? %>
                <li><%= link_to "Iniciar sesion", usuario_session_path %></li>
          <% else %>
           <li><%= link_to "Cerrar sesion", destroy_usuario_session_path, method: :delete %></li>

          <%end%>
         
            <li><%= link_to "Registrarse", new_organizacion_path %> </li>

      </ul>
      
    </div><!-- /.navbar-collapse -->

  </div>
  
  </div><!-- /.container-fluid -->
</nav>